### ISSUE TITLE
plans to merge back?

### ISSUE THREAD

**Issue by mikestaub** [Devpodio/devpodio#27]
### Description
Why is this hard fork needed? Do you plan on creating a PR with your improvements back to theia?

**Comment by uniibu** [comment]
This is basically just a personal fork which includes latest commits from Theia plus additional personal commits that I find beneficial for me. And yes I'm also a contributor at Theia. The commits here are also more on performance(for me) that never got pushed tru at theia due to some reasons such as asset splitting, cache busting, pwa etc..
